=== Natthaphatpiw/chatbot-computershop/schema.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "type": "object",
  "required": [
    "_id",
    "byOrder",
    "byOrderDate",
    "categoryId",
    "cateId",
    "cateName",
    "clearAnce",
    "compare",
    "createdAt",
    "description",
    "freeShipping",
    "highlights_detail",
    "id",
    "images",
    "logo",
    "preOrder",
    "preOrderDate",
    "price",
    "product360",
    "product_ict",
    "product_ict_comment",
    "product_warranty_2_year",
    "product_warranty_3_year",
    "product_windows",
    "productCode",
    "productLocation",
    "productView",
    "rating",
    "salePrice",
    "stockQuantity",
    "title",
    "totalReviews",
    "updatedAt"
  ],
  "properties": {
    "_id": {
      "$ref": "#/$defs/ObjectId"
    },
    "byOrder": {
      "type": "boolean"
    },
    "byOrderDate": {
      "type": "null"
    },
    "categoryId": {
      "type": "integer"
    },
    "cateId": {
      "type": "integer"
    },
    "cateName": {
      "type": "string"
    },
    "clearAnce": {
      "type": "boolean"
    },
    "compare": {
      "type": "object",
      "required": [
        "cate_sub1",
        "cate_sub2",
        "cate_sub3",
        "compare_lv"
      ],
      "properties": {
        "cate_sub1": {
          "type": "string"
        },
        "cate_sub2": {
          "type": "string"
        },
        "cate_sub3": {
          "type": "string"
        },
        "compare_lv": {
          "type": "integer"
        }
      }
    },
    "createdAt": {
      "$ref": "#/$defs/Date"
    },
    "description": {
      "type": "string"
    },
    "freeShipping": {
      "type": "boolean"
    },
    "highlights_detail": {
      "type": "string"
    },
    "id": {
      "type": "integer"
    },
    "images": {
      "type": "object",
      "required": [
        "icon",
        "large",
        "medium",
        "original",
        "small"
      ],
      "properties": {
        "icon": {
          "type": "object",
          "required": [
            "heigth",
            "url",
            "width"
          ],
          "properties": {
            "heigth": {
              "type": "string"
            },
            "url": {
              "type": "array",
              "items": {
                "type": "string"
              }
            },
            "width": {
              "type": "string"
            }
          }
        },
        "large": {
          "type": "object",
          "required": [
            "heigth",
            "url",
            "width"
          ],
          "properties": {
            "heigth": {
              "type": "string"
            },
            "url": {
              "type": "array",
              "items": {
                "type": "string"
              }
            },
            "width": {
              "type": "string"
            }
          }
        },
        "medium": {
          "type": "object",
          "required": [
            "heigth",
            "url",
            "width"
          ],
          "properties": {
            "heigth": {
              "type": "string"
            },
            "url": {
              "type": "array",
              "items": {
                "type": "string"
              }
            },
            "width": {
              "type": "string"
            }
          }
        },
        "original": {
          "type": "object",
          "required": [
            "heigth",
            "url",
            "width"
          ],
          "properties": {
            "heigth": {
              "type": "string"
            },
            "url": {
              "type": "array",
              "items": {
                "type": "string"
              }
            },
            "width": {
              "type": "string"
            }
          }
        },
        "small": {
          "type": "object",
          "required": [
            "heigth",
            "url",
            "width"
          ],
          "properties": {
            "heigth": {
              "type": "string"
            },
            "url": {
              "type": "array",
              "items": {
                "type": "string"
              }
            },
            "width": {
              "type": "string"
            }
          }
        }
      }
    },
    "logo": {
      "type": "object",
      "required": [
        "c_icon",
        "code",
        "code_discount",
        "freeItem",
        "freeItemOri",
        "icon_ai",
        "icon_asus",
        "icon_ict",
        "installment",
        "shipping",
        "show_on_web",
        "supplier"
      ],
      "properties": {
        "c_icon": {
          "type": [
            "string",
            "null"
          ]
        },
        "code": {
          "type": "string"
        },
        "code_discount": {
          "type": "string"
        },
        "freeItem": {
          "type": "object",
          "required": [
            "title",
            "url"
          ],
          "properties": {
            "title": {
              "type": "array",
              "items": {
                "type": "string"
              }
            },
            "url": {
              "type": "array",
              "items": {
                "type": "string"
              }
            }
          }
        },
        "freeItemOri": {
          "type": "object",
          "required": [
            "title",
            "url"
          ],
          "properties": {
            "title": {
              "type": "array",
              "items": {
                "type": "string"
              }
            },
            "url": {
              "type": "array",
              "items": {
                "type": "string"
              }
            }
          }
        },
        "icon_ai": {
          "type": [
            "null",
            "string"
          ]
        },
        "icon_asus": {
          "type": "null"
        },
        "icon_ict": {
          "type": "null"
        },
        "installment": {
          "type": "object",
          "required": [
            "logo_search",
            "title",
            "url"
          ],
          "properties": {
            "logo_search": {
              "anyOf": [
                {
                  "type": "null"
                },
                {
                  "type": "array",
                  "items": {
                    "type": "string"
                  }
                }
              ]
            },
            "title": {
              "type": "array",
              "items": {
                "type": "string"
              }
            },
            "url": {
              "type": "array",
              "items": {
                "type": "string"
              }
            }
          }
        },
        "shipping": {
          "type": "array",
          "items": {
            "type": "object",
            "required": [
              "key",
              "locationStatus",
              "title",
              "url"
            ],
            "properties": {
              "key": {
                "type": "string"
              },
              "locationStatus": {
                "type": "string"
              },
              "title": {
                "type": "string"
              },
              "url": {
                "type": "string"
              }
            }
          }
        },
        "show_on_web": {
          "type": "string"
        },
        "supplier": {
          "type": "array",
          "items": {
            "type": []
          }
        }
      }
    },
    "preOrder": {
      "type": "boolean"
    },
    "preOrderDate": {
      "type": [
        "null",
        "string"
      ]
    },
    "price": {
      "$ref": "#/$defs/Double"
    },
    "product360": {
      "type": "boolean"
    },
    "product_ict": {
      "type": [
        "null",
        "string"
      ]
    },
    "product_ict_comment": {
      "type": [
        "null",
        "string"
      ]
    },
    "product_warranty_2_year": {
      "type": "null"
    },
    "product_warranty_3_year": {
      "type": [
        "null",
        "string"
      ]
    },
    "product_windows": {
      "type": "null"
    },
    "productCode": {
      "type": "string"
    },
    "productLocation": {
      "type": "string"
    },
    "productView": {
      "type": "integer"
    },
    "rating": {
      "$ref": "#/$defs/Double"
    },
    "salePrice": {
      "$ref": "#/$defs/Double"
    },
    "stockQuantity": {
      "type": "integer"
    },
    "title": {
      "type": "string"
    },
    "totalReviews": {
      "type": "integer"
    },
    "updatedAt": {
      "anyOf": [
        {
          "$ref": "#/$defs/Date"
        },
        {
          "type": "null"
        }
      ]
    }
  },
  "$defs": {
    "ObjectId": {
      "type": "object",
      "properties": {
        "$oid": {
          "type": "string",
          "pattern": "^[0-9a-fA-F]{24}$"
        }
      },
      "required": [
        "$oid"
      ],
      "additionalProperties": false
    },
    "Double": {
      "oneOf": [
        {
          "type": "number"
        },
        {
          "type": "object",
          "properties": {
            "$numberDouble": {
              "enum": [
                "Infinity",
                "-Infinity",
                "NaN"
              ]
            }
          }
        }
      ]
    },
    "Date": {
      "type": "object",
      "properties": {
        "$date": {
          "type": "string",
          "format": "date-time"
        }
      },
      "required": [
        "$date"
      ],
      "additionalProperties": false
    }
  }
}

=== Natthaphatpiw/chatbot-computershop/dashboard-ai-data.products.json
[{
  "_id": {
    "$oid": "685827c746b7696e78ce8765"
  },
  "productCode": "X1504GA-NJ322W",
  "byOrder": false,
  "byOrderDate": null,
  "cateId": 25,
  "cateName": "Notebooks",
  "categoryId": 121,
  "clearAnce": false,
  "compare": {
    "cate_sub1": "24",
    "cate_sub2": "25",
    "cate_sub3": "121",
    "compare_lv": 2
  },
  "createdAt": {
    "$date": "2024-02-20T09:06:22.000Z"
  },
  "description": "• Intel Core i3-N305\r\n• 8GB DDR4 (ON BOARD)\r\n• 512GB PCIe/NVMe M.2 SSD\r\n• 15.6\" FHD Anti-Glare\r\n• Intel UHD Graphics (Integrated)\r\n• Windows 11 Home",
  "freeShipping": true,
  "highlights_detail": "",
  "id": 65577,
  "images": {
    "original": {
      "width": "0",
      "heigth": "0",
      "url": [
        "https://www.jib.co.th/img_master/product/original/20240220162537_65577_287_1.jpg"
      ]
    },
    "icon": {
      "width": "50px",
      "heigth": "50px",
      "url": [
        "https://www.jib.co.th/img_master/product/icon/20240220162537_65577_287_1.jpg"
      ]
    },
    "small": {
      "width": "150px",
      "heigth": "150px",
      "url": [
        "https://www.jib.co.th/img_master/product/small/20240220162537_65577_287_1.jpg"
      ]
    },
    "medium": {
      "width": "280px",
      "heigth": "280px",
      "url": [
        "https://www.jib.co.th/img_master/product/medium/20240220162537_65577_287_1.jpg"
      ]
    },
    "large": {
      "width": "550px",
      "heigth": "550px",
      "url": [
        "https://www.jib.co.th/img_master/product/big/20240220162537_65577_287_1.jpg"
      ]
    }
  },
  "logo": {
    "freeItemOri": {
      "url": [
        "https://www.jib.co.th/img_master/images/promotion/original/20240827102346_1.jpg"
      ],
      "title": [
        "( เฉพาะสั่งซื้อ ออนไลน์ เท่านั้น )  GIFTBOX JIB SMILEY FOR NOTEBOOK"
      ]
    },
    "shipping": [
      {
        "url": "",
        "title": "",
        "key": "",
        "locationStatus": ""
      }
    ],
    "installment": {
      "url": [
        "https://www.jib.co.th/img_master/img/zero-percent-kbank.png?v=1001",
        "https://www.jib.co.th/img_master/img/610517-logo-ktc2020-04-01.png?v=1003",
        "https://www.jib.co.th/img_master/img/logo-ผ่อนสินค้า-06.png?v=1004",
        "https://www.jib.co.th/img_master/img/kfc0-2020-03-24.png?v=1003"
      ],
      "title": [
        "เจไอบี มอบเเคมเปญ เเบ่งชำระ 0% ผ่านบัตรเครดิตของธนาคารกสิกรไทย",
        "เจไอบี มอบแคมเปญ แบ่งชำระ 0% ผ่านบัตรเครดิตของธนาคารกรุงไทย",
        "เจไอบี มอบแคมเปญ แบ่งชำระ 0% ผ่านบัตรเครดิตของธนาคารกรุงศรีอยุธยา",
        "เจไอบี มอบแคมเปญ แบ่งชำระ 0% ผ่านบัตรกรุงศรี เฟิร์สช้อยส์"
      ],
      "logo_search": [
        "kbank",
        "ktc",
        "kcc",
        "kfc"
      ]
    },
    "freeItem": {
      "url": [
        "https://www.jib.co.th/img_master/images/promotion/small/20240827102346_1.jpg"
      ],
      "title": [
        "( เฉพาะสั่งซื้อ ออนไลน์ เท่านั้น )  GIFTBOX JIB SMILEY FOR NOTEBOOK"
      ]
    },
    "code": "",
    "code_discount": "",
    "show_on_web": "",
    "supplier": [],
    "c_icon": null,
    "icon_ai": null,
    "icon_ict": null,
    "icon_asus": null
  },
  "preOrder": false,
  "preOrderDate": null,
  "price": 11990,
  "product360": true,
  "productLocation": "75",
  "productView": 38351,
  "product_ict": null,
  "product_ict_comment": null,
  "product_warranty_2_year": null,
  "product_warranty_3_year": null,
  "product_windows": null,
  "rating": 0,
  "salePrice": 10990,
  "stockQuantity": 2,
  "title": "NOTEBOOK (โน้ตบุ๊ค) ASUS VIVOBOOK GO 15 X1504GA-NJ322W (MIXED BLACK)",
  "totalReviews": 0,
  "updatedAt": {
    "$date": "2024-08-09T14:18:59.000Z"
  }
},
{
  "_id": {
    "$oid": "685827c746b7696e78ce8766"
  },
  "productCode": "M1504FA-NJ516W",
  "byOrder": false,
  "byOrderDate": null,
  "cateId": 25,
  "cateName": "Notebooks",
  "categoryId": 121,
  "clearAnce": false,
  "compare": {
    "cate_sub1": "24",
    "cate_sub2": "25",
    "cate_sub3": "121",
    "compare_lv": 2
  },
  "createdAt": {
    "$date": "2024-03-29T15:37:19.000Z"
  },
  "description": "• AMD Ryzen 5 7520U\r\n• 8GB LPDDR5 (ON BOARD)\r\n• 512GB PCIe/NVMe M.2 SSD\r\n• 15.6\" FHD Anti-Glare\r\n• AMD Radeon Graphics (Integrated)\r\n• Windows 11 Home",
  "freeShipping": true,
  "highlights_detail": "",
  "id": 66554,
  "images": {
    "original": {
      "width": "0",
      "heigth": "0",
      "url": [
        "https://www.jib.co.th/img_master/product/original/20240401145220_66554_287_1.jpg"
      ]
    },
    "icon": {
      "width": "50px",
      "heigth": "50px",
      "url": [
        "https://www.jib.co.th/img_master/product/icon/20240401145220_66554_287_1.jpg"
      ]
    },
    "small": {
      "width": "150px",
      "heigth": "150px",
      "url": [
        "https://www.jib.co.th/img_master/product/small/20240401145220_66554_287_1.jpg"
      ]
    },
    "medium": {
      "width": "280px",
      "heigth": "280px",
      "url": [
        "https://www.jib.co.th/img_master/product/medium/20240401145220_66554_287_1.jpg"
      ]
    },
    "large": {
      "width": "550px",
      "heigth": "550px",
      "url": [
        "https://www.jib.co.th/img_master/product/big/20240401145220_66554_287_1.jpg"
      ]
    }
  },
  "logo": {
    "freeItemOri": {
      "url": [
        "https://www.jib.co.th/img_master/images/promotion/original/20240827102346_1.jpg"
      ],
      "title": [
        "( เฉพาะสั่งซื้อ ออนไลน์ เท่านั้น )  GIFTBOX JIB SMILEY FOR NOTEBOOK"
      ]
    },
    "shipping": [
      {
        "url": "",
        "title": "",
        "key": "",
        "locationStatus": ""
      }
    ],
    "installment": {
      "url": [
        "https://www.jib.co.th/img_master/img/zero-percent-kbank.png?v=1001",
        "https://www.jib.co.th/img_master/img/610517-logo-ktc2020-04-01.png?v=1003",
        "https://www.jib.co.th/img_master/img/logo-ผ่อนสินค้า-06.png?v=1004",
        "https://www.jib.co.th/img_master/img/kfc0-2020-03-24.png?v=1003"
      ],
      "title": [
        "เจไอบี มอบเเคมเปญ เเบ่งชำระ 0% ผ่านบัตรเครดิตของธนาคารกสิกรไทย",
        "เจไอบี มอบแคมเปญ แบ่งชำระ 0% ผ่านบัตรเครดิตของธนาคารกรุงไทย",
        "เจไอบี มอบแคมเปญ แบ่งชำระ 0% ผ่านบัตรเครดิตของธนาคารกรุงศรีอยุธยา",
        "เจไอบี มอบแคมเปญ แบ่งชำระ 0% ผ่านบัตรกรุงศรี เฟิร์สช้อยส์"
      ],
      "logo_search": [
        "kbank",
        "ktc",
        "kcc",
        "kfc"
      ]
    },
    "freeItem": {
      "url": [
        "https://www.jib.co.th/img_master/images/promotion/small/20240827102346_1.jpg"
      ],
      "title": [
        "( เฉพาะสั่งซื้อ ออนไลน์ เท่านั้น )  GIFTBOX JIB SMILEY FOR NOTEBOOK"
      ]
    },
    "code": "",
    "code_discount": "",
    "show_on_web": "",
    "supplier": [],
    "c_icon": null,
    "icon_ai": null,
    "icon_ict": null,
    "icon_asus": null
  },
  "preOrder": false,
  "preOrderDate": null,
  "price": 13990,
  "product360": true,
  "productLocation": "75",
  "productView": 35075,
  "product_ict": null,
  "product_ict_comment": null,
  "product_warranty_2_year": null,
  "product_warranty_3_year": null,
  "product_windows": null,
  "rating": 0,
  "salePrice": 12990,
  "stockQuantity": 3,
  "title": "NOTEBOOK (โน้ตบุ๊ค) ASUS VIVOBOOK GO 15 M1504FA-NJ516W (MIXED BLACK)",
  "totalReviews": 0,
  "updatedAt": {
    "$date": "2024-10-08T10:54:36.000Z"
  }
},
{
  "_id": {
    "$oid": "685827c946b7696e78ce877e"
  },
  "productCode": "NX.J23ST.002",
  "byOrder": false,
  "byOrderDate": null,
  "cateId": 25,
  "cateName": "Notebooks",
  "categoryId": 32,
  "clearAnce": false,
  "compare": {
    "cate_sub1": "24",
    "cate_sub2": "25",
    "cate_sub3": "32",
    "compare_lv": 2
  },
  "createdAt": {
    "$date": "2024-11-13T15:54:14.000Z"
  },
  "description": "• Intel Core i3-1305U\r\n• 8GB DDR5\r\n• 512GB NVMe PCIe M.2 SSD\r\n• 16\" WUXGA (1920 x 1200) IPS Non-Touch\r\n• Intel Graphics (Integrated)\r\n• Windows 11 Home + Office Home & Student 2021",
  "freeShipping": true,
  "highlights_detail": "",
  "id": 72074,
  "images": {
    "original": {
      "width": "0",
      "heigth": "0",
      "url": [
        "https://www.jib.co.th/img_master/product/original/20241114133718_72074_287_1.jpg"
      ]
    },
    "icon": {
      "width": "50px",
      "heigth": "50px",
      "url": [
        "https://www.jib.co.th/img_master/product/icon/20241114133718_72074_287_1.jpg"
      ]
    },
    "small": {
      "width": "150px",
      "heigth": "150px",
      "url": [
        "https://www.jib.co.th/img_master/product/small/20241114133718_72074_287_1.jpg"
      ]
    },
    "medium": {
      "width": "280px",
      "heigth": "280px",
      "url": [
        "https://www.jib.co.th/img_master/product/medium/20241114133718_72074_287_1.jpg"
      ]
    },
    "large": {
      "width": "550px",
      "heigth": "550px",
      "url": [
        "https://www.jib.co.th/img_master/product/big/20241114133718_72074_287_1.jpg"
      ]
    }
  },
  "logo": {
    "freeItemOri": {
      "url": [
        "https://www.jib.co.th/img_master/images/promotion/original/20230627152606_1.jpg",
        "https://www.jib.co.th/img_master/images/promotion/original/20240827102346_1.jpg"
      ],
      "title": [
        "( เฉพาะสั่งซื้อ ออนไลน์ เท่านั้น ) BAG ACER PREDATOR CANVAS SLIM BACKPACK",
        "( เฉพาะสั่งซื้อ ออนไลน์ เท่านั้น )  GIFTBOX JIB SMILEY FOR NOTEBOOK"
      ]
    },
    "shipping": [
      {
        "url": "",
        "title": "",
        "key": "",
        "locationStatus": ""
      }
    ],
    "installment": {
      "url": [
        "https://www.jib.co.th/img_master/img/zero-percent-kbank.png?v=1001",
        "https://www.jib.co.th/img_master/img/610517-logo-ktc2020-04-01.png?v=1003",
        "https://www.jib.co.th/img_master/img/logo-ผ่อนสินค้า-06.png?v=1004",
        "https://www.jib.co.th/img_master/img/kfc0-2020-03-24.png?v=1003"
      ],
      "title": [
        "เจไอบี มอบเเคมเปญ เเบ่งชำระ 0% ผ่านบัตรเครดิตของธนาคารกสิกรไทย",
        "เจไอบี มอบแคมเปญ แบ่งชำระ 0% ผ่านบัตรเครดิตของธนาคารกรุงไทย",
